[package]
name = "proxy_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["net", "os-poll"] }
byteorder = "1.4"
chrono = "0.4"

[build]
target = "x86_64-unknown-linux-gnu"